---
 - name: install tomcat server
   hosts: all
   become: true
   become_user: root

   tasks:
   - name: install java
     yum:
      name: java-1.8*

   - name: download tomcat server packages
     get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
       dest: /usr/local

   - name: extract tomcat packages
     unarchive:
       src: /usr/local/apache-tomcat-10.0.27.tar.gz
       dest: /usr/local
       remote_src: yes

   - name: deploying the new WAR-file to target servers
     copy:
        src: /var/lib/jenkins/workspace/project2/target/webapp-0.2.war
        dest: /home/centos/tomcat-10.0.27
        mode: 0755

   - name: Install GIT
     yum:
      name: git
      state: present

   - name: test connection
     ansible.builtin.ping:

   - name: clone git repo
     git:
       repo: https://github.com/ADENIKE2010/JavaWebCalculator.git
       dest: /var/www/html
       clone: yes
       accept_hostkey: yes

   - name: start tomcat services
     shell: nohup /usr/local/apache-tomcat-10.0.27/bin/startup.sh
...

