---
- name: Install Apache Tomcat10 using ansible
  hosts: all
  become: true
  tasks:
    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      yum:
        name: java-1.8*
        state: present

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: download tomcat server packages
      get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
       dest: /usr/local

    - name: extract tomcat packages
      unarchive:
       src: /usr/local/apache-tomcat-10.0.27.tar.gz
       dest: /usr/local
       remote_src: yes

    - name: Install GIT
      yum:
        name: git
        state: present

    - name: clone git repo
      git:
       repo: https://github.com/ADENIKE2010/JavaWebCalculator.git
       dest: /var/www/html
        
    - name: deploying the new WAR-file to target servers
      copy:
        src: /var/lib/jenkins/workspace/project2/target/webapp-0.2.war
        dest: /home/ubuntu/
        mode: 0755
 
    - name: start tomcat services
      shell: nohup /usr/local/apache-tomcat-10.0.27/bin/startup.sh        
...

